# Generated by Django 5.2.7 on 2025-11-29 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(max_length=500)),
                ('category', models.CharField(choices=[('HOTEL', 'Hotel'), ('ROOM', 'Room'), ('DINING', 'Dining'), ('FACILITIES', 'Facilities'), ('EVENTS', 'Events'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gallery_images',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
