# Generated by Django 5.2.9 on 2025-12-11 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Gallery Categories',
                'db_table': 'gallery_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['category', 'order', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='title',
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=200),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.gallerycategory'),
        ),
    ]
