# Generated by Django 5.2.9 on 2025-12-11 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_gallerycategory_alter_galleryimage_options_and_more'),
    ]

    operations = [
    ]
