# Generated by Django 5.2.7 on 2025-11-30 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('STAFF', 'Staff'), ('GUEST', 'Guest'), ('CUSTOMER', 'Customer')], default='CUSTOMER', max_length=10),
        ),
    ]
