# Generated by Django 5.2.7 on 2025-11-29 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/'),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
