# Generated by Django 5.2.9 on 2025-12-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_roomavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='accessible_bathroom',
            field=models.BooleanField(default=False, verbose_name='Accessible Bathroom Features'),
        ),
        migrations.AddField(
            model_name='room',
            name='air_conditioning',
            field=models.BooleanField(default=True, verbose_name='Air Conditioning/Heating'),
        ),
        migrations.AddField(
            model_name='room',
            name='bathroom_features',
            field=models.TextField(blank=True, help_text="Comma-separated list: e.g., 'Toiletries, Hairdryer, Towels, Bathrobe, Slippers'"),
        ),
        migrations.AddField(
            model_name='room',
            name='bed_configuration',
            field=models.CharField(choices=[('SINGLE', 'Single Bed'), ('DOUBLE', 'Double Bed'), ('QUEEN', 'Queen Bed'), ('KING', 'King Bed'), ('TWIN', 'Twin Beds'), ('BUNK', 'Bunk Beds')], default='QUEEN', help_text='Type of bed(s) in the room', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='check_in_time',
            field=models.TimeField(blank=True, help_text='Standard check-in time', null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='check_out_time',
            field=models.TimeField(blank=True, help_text='Standard check-out time', null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='coffee_maker',
            field=models.BooleanField(default=True, verbose_name='Coffee & Tea Maker'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_balcony',
            field=models.BooleanField(default=False, verbose_name='Balcony/Terrace'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_kitchenette',
            field=models.BooleanField(default=False, verbose_name='Kitchenette/Full Kitchen'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_seating_area',
            field=models.BooleanField(default=False, verbose_name='In-Room Seating Area'),
        ),
        migrations.AddField(
            model_name='room',
            name='iron_board',
            field=models.BooleanField(default=True, verbose_name='Iron & Ironing Board'),
        ),
        migrations.AddField(
            model_name='room',
            name='is_soundproof',
            field=models.BooleanField(default=False, verbose_name='Soundproofing'),
        ),
        migrations.AddField(
            model_name='room',
            name='max_occupancy',
            field=models.PositiveIntegerField(default=2, help_text='Maximum number of guests'),
        ),
        migrations.AddField(
            model_name='room',
            name='minibar',
            field=models.BooleanField(default=False, verbose_name='Mini-bar/Fridge'),
        ),
        migrations.AddField(
            model_name='room',
            name='number_of_beds',
            field=models.PositiveIntegerField(default=1, help_text='Number of beds'),
        ),
        migrations.AddField(
            model_name='room',
            name='pet_policy',
            field=models.CharField(choices=[('NOT_ALLOWED', 'Pets Not Allowed'), ('ALLOWED', 'Pets Allowed'), ('ON_REQUEST', 'Pets Allowed on Request')], default='NOT_ALLOWED', max_length=20, verbose_name='Pet Policy'),
        ),
        migrations.AddField(
            model_name='room',
            name='safe',
            field=models.BooleanField(default=True, verbose_name='In-Room Safe'),
        ),
        migrations.AddField(
            model_name='room',
            name='smoking_policy',
            field=models.CharField(choices=[('NON_SMOKING', 'Non-Smoking'), ('SMOKING', 'Smoking Allowed'), ('DESIGNATED_AREA', 'Designated Smoking Area')], default='NON_SMOKING', max_length=20, verbose_name='Smoking Policy'),
        ),
        migrations.AddField(
            model_name='room',
            name='special_perks',
            field=models.TextField(blank=True, help_text='Special perks like welcome gifts, luxury toiletries, etc.'),
        ),
        migrations.AddField(
            model_name='room',
            name='storage',
            field=models.BooleanField(default=True, verbose_name='Wardrobe/Closet'),
        ),
        migrations.AddField(
            model_name='room',
            name='telephone',
            field=models.BooleanField(default=True, verbose_name='Telephone'),
        ),
        migrations.AddField(
            model_name='room',
            name='tv',
            field=models.BooleanField(default=True, verbose_name='TV/Entertainment System'),
        ),
        migrations.AddField(
            model_name='room',
            name='view_type',
            field=models.CharField(choices=[('CITY', 'City View'), ('SEA', 'Sea View'), ('GARDEN', 'Garden View'), ('MOUNTAIN', 'Mountain View'), ('POOL', 'Pool View'), ('COURTYARD', 'Courtyard View'), ('NO_VIEW', 'No Specific View')], default='NO_VIEW', max_length=20, verbose_name='View Type'),
        ),
        migrations.AddField(
            model_name='room',
            name='virtual_tour_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Virtual Tour/Video URL'),
        ),
        migrations.AddField(
            model_name='room',
            name='wheelchair_accessible',
            field=models.BooleanField(default=False, verbose_name='Wheelchair Accessible'),
        ),
        migrations.AddField(
            model_name='room',
            name='wifi',
            field=models.BooleanField(default=True, verbose_name='Free Wi-Fi'),
        ),
        migrations.AddField(
            model_name='room',
            name='work_desk',
            field=models.BooleanField(default=True, verbose_name='Work Desk/Workspace'),
        ),
    ]
